name: Update Nix dependencies.

on:
  workflow_dispatch:
  schedule:
    # 11 pm every Wednesday
    - cron: "0 23 * * 3"

jobs:
  update-nix-dependencies:
    uses: hackworthltd/.github/.github/workflows/reusable-update-nix-flake-public.yml@main
